
"""
Example Usage:
--------------
To generate a CSV file for a circular trajectory, use the following code snippet:

create_active_csv(shape_name="circle", diameter=5.0, direction=1, maneuver_time=60.0, start_x=0.0, start_y=0.0, initial_altitude=10.0, climb_rate=2.0, move_speed=2.5, hold_time=2.0)

Visualization:
--------------
After generating the CSV file, you can visualize the trajectory using plot functions and save the trajectory plot in the "shaped" folder along with the CSV file.

Note:
-----
Make sure to have the necessary dependencies installed and correctly set up the offboard control system to use the generated CSV file for controlling the drone in an offboard mode.

Usage:
------
The output generated by `csvCreator.py` can be utilized in the `offboard_from_csv.py` file, also available in the same GitHub repository, to control a drone in an offboard mode. The generated CSV file contains the necessary information for each step of the drone's trajectory, including position, velocity, acceleration, yaw angle, and LED colors.

Offboard Control in PX4:
------------------------
Chế độ offboard trong PX4 là một chế độ bay cho phép các hệ thống bên ngoài điều khiển trực tiếp vị trí và vận tốc của drone. Nó cho phép bay tự động và thường được sử dụng trong nghiên cứu, phát triển và các kịch bản thử nghiệm. Hệ thống điều khiển offboard giao tiếp với bộ điều khiển bay của drone qua một giao thức giao tiếp như MAVLink.

Để sử dụng đầu ra CSV được tạo bởi csvCreator.py cho việc điều khiển offboard trong PX4, bạn có thể thực hiện theo các bước sau:

1. Tải file CSV đã tạo, đại diện cho quỹ đạo mong muốn cho drone.
2. Trích xuất thông tin vị trí và vận tốc từ file CSV.
3. Gửi các lệnh vị trí và vận tốc đến bộ điều khiển bay của drone bằng cách sử dụng hệ thống điều khiển offboard, chẳng hạn như script offboard_from_csv.py.
4. Bộ điều khiển bay sẽ giải thích các lệnh và thực hiện quỹ đạo mong muốn, hướng dẫn drone theo đúng quỹ đạo.
"""

import csv
import math
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
from functions.export_and_plot_shape import export_and_plot_shape
from functions.trajectories import *
from functions.create_active_csv import create_active_csv

# Example usage
shape_name="heart_shape"
diameter = 30.0
direction = 1
maneuver_time = 90.0
start_x = 0
start_y = 0
initial_altitude = 15
climb_rate = 1.0
move_speed = 2.0  # m/s
hold_time = 4.0 #s
step_time = 0.1 #s
output_file = "shapes/active.csv"

create_active_csv(
    shape_name=shape_name,
    diameter=diameter,
    direction=direction,
    maneuver_time=maneuver_time,
    start_x=start_x,
    start_y=start_y,
    initial_altitude=initial_altitude,
    climb_rate=climb_rate,
    move_speed = move_speed,
    hold_time = hold_time,
    step_time = step_time,
    output_file = output_file,
)

output_file = "shapes/active.csv"
export_and_plot_shape(output_file)

